version: "3"

services:

    node:
        image: silolabima2/kinerja:0.0.1
        container_name: kinerja
        ports:
            - "8080:4000"
        networks:
            - docker-service
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb-secret
        secrets:
            - mariadb-secret
        volumes:
            - mariadb-data:/data/db
        networks:
            - docker-service

networks:
    docker-service:
        driver: bridge

volumes:
    mariadb-data:
        driver: local

secrets:
    mariadb-secret:
        file: ./.maria-env
