services:
    node:
        image: silolabima2/kinerja:0.0.1
        container_name: kinerja
        ports:
            - "8080:4000"
        networks:
            - docker_service
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mariadb_secret
        secrets:
            - mariadb_secret
        volumes:
            - mariadb_data:/data/db
        networks:
            - docker_service
    networks:
        docker_service:
            driver: bridge
    volumes:
        mariadb_data:
            driver: local
    secrets:
        mariadb_secret:
            file: ./.maria_env
